name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop

jobs:
  claude-code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Claude Code Review
        uses: anthropic/claude-code-review-action@v1
        with:
          # Anthropic API key (required)
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          
          # GitHub token for commenting (required)
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
          # Model configuration (optional)
          model: claude-3-5-sonnet-20241022
          
          # Review configuration (optional)
          max-tokens: 4000
          temperature: 0.1
          
          # File patterns to include/exclude (optional)
          include-patterns: |
            *.py
            *.js
            *.ts
            *.jsx
            *.tsx
            *.md
            *.yml
            *.yaml
            *.json
          
          exclude-patterns: |
            node_modules/**
            .venv/**
            __pycache__/**
            *.pyc
            dist/**
            build/**
            .git/**
            logs/**
          
          # Review focus areas (optional)
          focus-areas: |
            - Code quality and best practices
            - Test coverage and correctness
            - Security vulnerabilities
            - Performance issues
            - Documentation completeness
            - TDD compliance and test structure
            - Error handling and edge cases
          
          # Custom instructions (optional)
          custom-instructions: |
            This is a Python MCP (Model Context Protocol) server project using FastAPI.
            Please pay special attention to:
            - Test-driven development (TDD) practices
            - Proper error handling and logging
            - MCP protocol compliance
            - API design and documentation
            - Python coding standards (PEP 8)
            - Dependency management with uv
            
      - name: Comment summary on PR
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const { context } = github;
            const pr_number = context.issue.number;
            
            // Add a summary comment
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: `🤖 **Claude Code Review completed!**
              
              The automated code review has been completed by Claude AI. Please check the individual line comments above for detailed feedback.
              
              **Review Focus Areas:**
              - Code quality and best practices ✅
              - Test coverage and correctness ✅
              - Security vulnerabilities ✅
              - Performance issues ✅
              - TDD compliance ✅
              
              Generated by [Claude Code Review Action](https://github.com/anthropic/claude-code-review-action)`
            });